console.log("Doodle Library Linked!");

const doodleLibrary = [
	{
		name: "SNAKEY",
		id: "snakey",
		health: 30,
		strength: 2,
		blockHurt: 2,
		setSpecial () { },
		clearSpecial () { },
		src: "images/snakey.png",
		attackAnimation () { },		
	},
	{
		name: "SUAVE BOX",
		id: "suave-box",
		health: 30,
		strength: 2,
		blockHurt: 2,
		setSpecial () { },
		clearSpecial () { },
		src: "images/suave-box.png",
		attackAnimation () { },
	},
	{
		name: "THE BIG NOPE",
		id: "big-nope",
		health: 30,
		strength: 2,
		blockHurt: 2,
		setSpecial () { },
		clearSpecial () { },
		src: "images/big-nope.png",
		attackAnimation () { },				
	},
	{
		name: "TRIANGLE MAN",
		id: "triangle-man",		
		health: 30,
		strength: 2,
		blockHurt: 2,
		setSpecial () { },
		clearSpecial () { },		
		src: "images/triangle-man.png",
		attackAnimation () { },				
	},
	{
		name: "PARTICLE MAN",
		id: "particle-man",
		health: 30,
		strength: 2,
		blockHurt: 2,
		setSpecial () { },
		clearSpecial () { },
		src: "images/particle-man.png",
		attackAnimation () { },	
	},
	{
		name: "PROBLEMATIC DOG",
		id: "problematic-dog",		
		health: 30,
		strength: 2,
		blockHurt: 2,
		setSpecial () { },
		clearSpecial () { },
		src: "images/problematic-dog.png",
		attackAnimation () { },	
	},
	{
		name: "WEDGE BUG",
		id: "wedge-bug",		
		health: 30,
		strength: 2,
		blockHurt: 2,
		setSpecial () { },
		clearSpecial () { },
		src: "images/wedge-bug.png",
		attackAnimation () { },	
	},
	{
		name: "CAT BAT",
		id: "cat-bat",
		health: 30,
		strength: 2,
		blockHurt: 2,
		setSpecial () { },
		clearSpecial () { },
		src: "images/cat-bat.png",
		attackAnimation () { },	
	},
	{
		name: "WILY WISP", 
		id: "wily-wisp",	
		health: 30,
		strength: 2,
		blockHurt: 2,
		setSpecial () { },
		clearSpecial () { },
		src: "images/wily-wisp.png",
		attackAnimation () { },	
	},
	{
		name: "LIL' GUY",
		id: "lil-guy",
		health: 30,
		strength: 2,
		blockHurt: 2,
		setSpecial () { },
		clearSpecial () { },
		src: "images/lil-guy.png",
		attackAnimation () { },
	}
]