console.log("Doodle Library Linked!");

const doodleLibrary = [
	{
		health: 30,
		strength: 2,
		blockHurt: 2,
		setSpecial () { },
		clearSpecial () { },
		name: "snakey",
		src: "images/big-blob.png",
		width: 200,
		height: 200,
	},
	{
		health: 30,
		strength: 2,
		blockHurt: 2,
		setSpecial () { },
		clearSpecial () { },
		name: "suave box",
		src: "images/big-lilguy.png",
		width: 200, 
		height: 200,
	},
	{
		health: 30,
		strength: 2,
		blockHurt: 2,
		setSpecial () { },
		clearSpecial () { },
		name: "nope",
		src: "images/big-nope.png",
		width: 200,
		height: 200,
	},
	{
		health: 30,
		strength: 2,
		blockHurt: 2,
		setSpecial () { },
		clearSpecial () { },		
		name: "triangle man",
		src: "images/big-wedge.png",
		width: 200,
		height: 200,
	},
	{
		health: 30,
		strength: 2,
		blockHurt: 2,
		setSpecial () { },
		clearSpecial () { },
		name: "particle man",
		src: "images/blob.png",
		width: 200, 
		height: 200,
	}
]