console.log("Doodle Library Linked!");

const doodleLibrary = [
	{
		name: "SNAKEY",
		health: 30,
		strength: 2,
		blockHurt: 2,
		setSpecial () { },
		clearSpecial () { },
		src: "images/snakey.png",
		attackAnimation () { },		
	},
	{
		name: "SUAVE BOX",
		health: 30,
		strength: 2,
		blockHurt: 2,
		setSpecial () { },
		clearSpecial () { },
		src: "images/suave-box.png",
		attackAnimation () { },
	},
	{
		name: "THE BIG NOPE",
		health: 30,
		strength: 2,
		blockHurt: 2,
		setSpecial () { },
		clearSpecial () { },
		src: "images/big-nope.png",
		attackAnimation () { },				
	},
	{
		name: "TRIANGLE MAN",		
		health: 30,
		strength: 2,
		blockHurt: 2,
		setSpecial () { },
		clearSpecial () { },		
		src: "images/triangle-man.png",
		attackAnimation () { },				
	},
	{
		name: "PARTICLE MAN",
		health: 30,
		strength: 2,
		blockHurt: 2,
		setSpecial () { },
		clearSpecial () { },
		src: "images/particle-man.png",
		attackAnimation () { },	
	},
	{
		name: "PROBLEMATIC DOG",		
		health: 30,
		strength: 2,
		blockHurt: 2,
		setSpecial () { },
		clearSpecial () { },
		src: "images/problematic-dog.png",
		attackAnimation () { },	
	},
	{
		name: "WEDGE BUG",		
		health: 30,
		strength: 2,
		blockHurt: 2,
		setSpecial () { },
		clearSpecial () { },
		src: "images/wedge-bug.png",
		attackAnimation () { },	
	},
	{
		name: "CAT BAT",
		health: 30,
		strength: 2,
		blockHurt: 2,
		setSpecial () { },
		clearSpecial () { },
		src: "images/cat-bat.png",
		attackAnimation () { },	
	},
	{
		name: "WILY WISP",		
		health: 30,
		strength: 2,
		blockHurt: 2,
		setSpecial () { },
		clearSpecial () { },
		src: "images/wily-wisp.png",
		attackAnimation () { },	
	},
	{
		name: "LIL' GUY",
		health: 30,
		strength: 2,
		blockHurt: 2,
		setSpecial () { },
		clearSpecial () { },
		src: "images/lil-guy.png",
		attackAnimation () { },
	}
]